- hosts: all
  collections:
   - redhat.insights
  tasks:
  - name: Ensure Insights is installed
    yum:
      name: insights-client
      state: present
  - name: Ensure that Insights client is registered to Satellite or cloud.redhat.com
    insights_register:
      state: present
